### ISSUE TITLE
spring-boot remote tutorial not work due to  class configured for PasswordFactory (provider: WildFlyElytron) cannot be found.

### ISSUE THREAD

**Issue by ryanzhang** [infinispan/infinispan-simple-tutorials#104]
I tried to run spring-boot/remote tutorial. (I run branch 10.1.x). It will fail to me. 

How to reproduce:
git branch: 10.1.x

mvn -version                                                                           
Apache Maven 3.6.1 (Red Hat 3.6.1-5)
Maven home: /usr/share/maven
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-11.0.6.10-0.fc32.x86_64
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.6.14-300.fc32.x86_64", arch: "amd64", family: "unix"

1) start infinispan by:
```bash
sudo podman run -it -p 11222:11222 -e USER="infinispan" -e PASS="infinispan" infinispan/server:10.1.6.Final
```
2) cd spring-boot/remote
mvn clean spring-boot:run
*It will report the first error*:
Caused by: org.infinispan.client.hotrod.exceptions.HotRodClientException: java.lang.SecurityException: ISPN006017: Unauthorized 'EXEC' operation

(It makes sense since I need to configure the auth-username and auth-password to springboot application)

Then I added the following in application.properties :
```properties
infinispan.remote.server-list=localhost:11222
# Uncomment client-intelligence if you are running infinispan with docker for mac
# Read https://blog.infinispan.org/2018/03/accessing-infinispan-inside-docker-for.html
# infinispan.remote.client-intelligence=BASIC
infinispan.remote.auth-username=infinispan
infinispan.remote.auth-password=infinispan
infinispan.remote.use-auth=true
```
Run again
mvn clean spring-boot:run
*Then I got the second error*:
```
2020-05-28 09:52:57.923  INFO 381786 --- [           main] o.i.t.s.spring.remote.RemoteClientApp    : Starting RemoteClientApp on smokingwell with PID 381786 (/wdc/github/redhat/infinispan-simple-tutorials/spring-boot/remote/target/classes started by rzhang in /wdc/github/redhat/infinispan-simple-tutorials/spring-boot/remote)
2020-05-28 09:52:57.925  INFO 381786 --- [           main] o.i.t.s.spring.remote.RemoteClientApp    : No active profile set, falling back to default profiles: default
2020-05-28 09:52:58.928  INFO 381786 --- [           main] org.infinispan.HOTROD                    : ISPN004021: Infinispan version: Infinispan 'Turia' 10.1.6.Final
2020-05-28 09:53:00.110 ERROR 381786 --- [-async-pool-1-7] org.infinispan.HOTROD                    : ISPN004007: Exception encountered. Retry 10 out of 10

org.infinispan.client.hotrod.exceptions.TransportException: javax.security.sasl.SaslException: ELY05051: Callback handler does not support credential acquisition [Caused by java.security.NoSuchAlgorithmException: class configured for PasswordFactory (provider: WildFlyElytron) cannot be found.]
        at org.infinispan.client.hotrod.impl.transport.netty.ActivationHandler.exceptionCaught(ActivationHandler.java:53) ~[infinispan-client-hotrod-10.1.6.Final.jar:10.1.6.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:300) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:279) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:271) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:300) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:279) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler.lambda$channelActive$2(AuthHandler.java:87) ~[infinispan-client-hotrod-10.1.6.Final.jar:10.1.6.Final]
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[na:na]
        at org.infinispan.client.hotrod.impl.operations.HotRodOperation.complete(HotRodOperation.java:165) ~[infinispan-client-hotrod-10.1.6.Final.jar:10.1.6.Final]
        at org.infinispan.client.hotrod.impl.operations.AuthOperation.acceptResponse(AuthOperation.java:64) ~[infinispan-client-hotrod-10.1.6.Final.jar:10.1.6.Final]
        at org.infinispan.client.hotrod.impl.transport.netty.HeaderDecoder.decode(HeaderDecoder.java:145) ~[infinispan-client-hotrod-10.1.6.Final.jar:10.1.6.Final]
        at org.infinispan.client.hotrod.impl.transport.netty.HintedReplayingDecoder.callDecode(HintedReplayingDecoder.java:94) ~[infinispan-client-hotrod-10.1.6.Final.jar:10.1.6.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:4.1.45.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:4.1.45.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: javax.security.sasl.SaslException: ELY05051: Callback handler does not support credential acquisition
        at org.wildfly.security.mechanism._private.MechanismUtil.getPasswordCredential(MechanismUtil.java:139) ~[wildfly-elytron-mechanism-1.10.4.Final.jar:1.10.4.Final]
        at org.wildfly.security.mechanism.scram.ScramClient.handleInitialChallenge(ScramClient.java:245) ~[wildfly-elytron-mechanism-scram-1.10.4.Final.jar:1.10.4.Final]
        at org.wildfly.security.sasl.scram.ScramSaslClient.evaluateMessage(ScramSaslClient.java:75) ~[wildfly-elytron-sasl-scram-1.10.4.Final.jar:1.10.4.Final]
        at org.wildfly.security.sasl.util.AbstractSaslParticipant.evaluateMessage(AbstractSaslParticipant.java:219) ~[wildfly-elytron-sasl-1.10.4.Final.jar:1.10.4.Final]
        at org.wildfly.security.sasl.util.AbstractSaslClient.evaluateChallenge(AbstractSaslClient.java:98) ~[wildfly-elytron-sasl-1.10.4.Final.jar:1.10.4.Final]
        at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler.evaluateChallenge(AuthHandler.java:106) ~[infinispan-client-hotrod-10.1.6.Final.jar:10.1.6.Final]
        at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler.access$200(AuthHandler.java:26) ~[infinispan-client-hotrod-10.1.6.Final.jar:10.1.6.Final]
        at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler$ChallengeEvaluator.apply(AuthHandler.java:124) ~[infinispan-client-hotrod-10.1.6.Final.jar:10.1.6.Final]
        at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler$ChallengeEvaluator.apply(AuthHandler.java:110) ~[infinispan-client-hotrod-10.1.6.Final.jar:10.1.6.Final]
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[na:na]
        ... 26 common frames omitted
Caused by: java.security.NoSuchAlgorithmException: class configured for PasswordFactory (provider: WildFlyElytron) cannot be found.
        at java.base/java.security.Provider$Service.getImplClass(Provider.java:1863) ~[na:na]
        at java.base/java.security.Provider$Service.newInstance(Provider.java:1824) ~[na:na]
        at org.wildfly.security.password.PasswordFactory.getInstance(PasswordFactory.java:119) ~[wildfly-elytron-credential-1.10.4.Final.jar:1.10.4.Final]
        at org.wildfly.security.mechanism._private.MechanismUtil.getPasswordCredential(MechanismUtil.java:78) ~[wildfly-elytron-mechanism-1.10.4.Final.jar:1.10.4.Final]
        ... 35 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.wildfly.security.password.impl.PasswordFactorySpiImpl
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
        at java.base/java.security.Provider$Service.getImplClass(Provider.java:1850) ~[na:na]
        ... 38 common frames omitted
```

**Comment by karesti** [comment]
I've opened a JIRA issue! thanks for reporting https://issues.redhat.com/browse/ISPN-12512

**Comment by fmonorchio** [comment]
I have the same problem using Micronaut Cache.

Server version: 12.0
Client dependencies: 12.0.1

The error seems the same:
org.infinispan.client.hotrod.exceptions.TransportException:: javax.security.sasl.SaslException: ELY05051: Callback handler does not support credential acquisition [Caused by java.security.NoSuchAlgorithmException: class configured for PasswordFactory (provider: WildFlyElytronSaslScramProvider) cannot be found.

How can I fix this?
Thanks

**Comment by tristantarrant** [comment]
Upgrade to Infinispan 12.1 please
