### ISSUE TITLE
Error running Spring boot remote examples

### ISSUE THREAD

**Issue by metametametameta** [infinispan/infinispan-simple-tutorials#137]
Running the spring boot session remote example from https://github.com/infinispan/infinispan-simple-tutorials/blob/12.1.x/spring-integration/spring-boot/session-remote/src/main/java/org/infinispan/tutorial/simple/spring/session/InfinispanConfiguration.java  throws the following exception on startup.  There's a similar issue when running just the Spring boot remote example as well (without sessions)

The main issue issue seems to be "Cannot find transcoder between 'application/x-java-object' to 'application/x-java-serialized'**

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionRepositoryFilterRegistration' defined in class path resource [org/springframework/boot/autoconfigure/session/SessionRepositoryFilterConfiguration.class]: Unsatisfied dependency expressed through method 'sessionRepositoryFilterRegistration' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'springSessionRepositoryFilter' defined in org.infinispan.spring.remote.session.configuration.InfinispanRemoteHttpSessionConfiguration: Unsatisfied dependency expressed through method 'springSessionRepositoryFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionRepository' defined in org.infinispan.spring.remote.session.configuration.InfinispanRemoteHttpSessionConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.infinispan.spring.remote.session.InfinispanRemoteSessionRepository]: Factory method 'sessionRepository' threw exception; nested exception is org.infinispan.client.hotrod.exceptions.HotRodClientException:Request for messageId=6 returned server error (status=0x85): org.infinispan.commons.CacheConfigurationException: Unable to inject dependencies for component class org.infinispan.encoding.DataConversion, path org.infinispan.AdvancedCache (a org.infinispan.cache.impl.EncoderCache)
org.infinispan.commons.dataconversion.EncodingException: ISPN000492: **Cannot find transcoder between 'application/x-java-object' to 'application/x-java-serialized'**
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.4.jar:5.3.4]
```

**Comment by pruivo** [comment]
what steps did you run?

I've just tried sessions-remote and it is working for me.

**Comment by gustavonalle** [comment]
That media type `application/x-java-serialized`  doesn't exist. The correct is `application/x-java-serialized-object`

**Comment by pruivo** [comment]
the tutorial is using protostream @gustavonalle 
https://github.com/infinispan/infinispan-simple-tutorials/blob/12.1.x/spring-integration/spring-boot/session-remote/src/main/java/org/infinispan/tutorial/simple/spring/session/InfinispanConfiguration.java#L19

It is not clear where `application/x-java-object` /  `application/x-java-serialized` come from :/

**Comment by metametametameta** [comment]
First I downloaded Infinispan server version 12.1.7 and started it up successfully on the command line so that the spring sessions sample can connect to it.

I then loaded up the simple tutorial samples into Spring Tools for Eclipse and ran the spring sessions remote sample as a Spring boot app with no modifications I see that the tutorial uses protostream - so no idea why it's complaining about application/x-java-serialized - I didn't modify anything in the sample. Is there a "hidden" cache that's triggering the error?

Interestingly, it seems to be just something on startup and not clear where application/x-java-object / application/x-java-serialized are coming from. I don't see any error in the Infinispan server log either.

Note that the spring embedded samples (sans remote) and even just regular remote samples (sans Spring) are working fine. It's only the remote-spring combo that seems to be failing.

**Comment by metametametameta** [comment]
I used a different name for the "sessions" cache and it worked! Looks like there is an old cache called "sessions" on my Infinispan server that I apparently managed to create earlier in a different test with a bad encoding (application/x-java-serialized). The bad sessions cache was also having server-wide effects in unrelated samples. Going to delete the bad cache. 

Thanks for your help.

A side question: the user guide for Infinispan Spring Boot Starter says this:

> By default Infinispan server uses a ProtoStream serialization library as the default marshaller. However, the ProtoStream marshaller is not supported for Spring integration. For this reason you should use the Java Serialization Marshaller.

Is this still true? The spring samples use protostream now. So we can use either Java ser. or Protostream as needed?

**Comment by pruivo** [comment]
The stable docs (Infinispan 12.1) does not say that, see [1]. 
Protostream support in Spring Boot Starter was added in Infinispan 12.1; any older version requires Java serialization.

[1] https://infinispan.org/docs/stable/titles/spring_boot/starter.html#spring-boot-serialization_remote

**Comment by metametametameta** [comment]
@pruivo Great. Thanks for the clarification & appreciate the help.

> 
> 
> The stable docs (Infinispan 12.1) does not say that, see [1].
> Protostream support in Spring Boot Starter was added in Infinispan 12.1; any older version requires Java serialization.
> 
> [1] https://infinispan.org/docs/stable/titles/spring_boot/starter.html#spring-boot-serialization_remote

**Comment by karesti** [comment]
@metametametameta can we close this issue then ?

**Comment by metametametameta** [comment]
Hi @karesti Yes, please close the issue.
